/*
 * Dynatrace Environment API
 *  Documentation of the Dynatrace Environment API v2. Resources here generally supersede those in v1. Migration of resources from v1 is in progress.   If you miss a resource, consider using the Dynatrace Environment API v1. To read about use cases and examples, see [Dynatrace Documentation](https://dt-url.net/2u23k1k) .  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.envv2.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dynatrace.apis.envv2.model.LocationExecutionResults;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Results of the execution of all HTTP monitor&#39;s requests.
 */
@ApiModel(description = "Results of the execution of all HTTP monitor's requests.")
@JsonPropertyOrder({
  MonitorExecutionResults.JSON_PROPERTY_MONITOR_ID,
  MonitorExecutionResults.JSON_PROPERTY_LOCATIONS_EXECUTION_RESULTS
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-02T15:08:06.080821500+01:00[Europe/Brussels]")
public class MonitorExecutionResults {
  public static final String JSON_PROPERTY_MONITOR_ID = "monitorId";
  private String monitorId;

  public static final String JSON_PROPERTY_LOCATIONS_EXECUTION_RESULTS = "locationsExecutionResults";
  private List<LocationExecutionResults> locationsExecutionResults = null;

  public MonitorExecutionResults() { 
  }

  public MonitorExecutionResults monitorId(String monitorId) {
    this.monitorId = monitorId;
    return this;
  }

   /**
   * Monitor id.
   * @return monitorId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Monitor id.")
  @JsonProperty(JSON_PROPERTY_MONITOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMonitorId() {
    return monitorId;
  }


  @JsonProperty(JSON_PROPERTY_MONITOR_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMonitorId(String monitorId) {
    this.monitorId = monitorId;
  }


  public MonitorExecutionResults locationsExecutionResults(List<LocationExecutionResults> locationsExecutionResults) {
    this.locationsExecutionResults = locationsExecutionResults;
    return this;
  }

  public MonitorExecutionResults addLocationsExecutionResultsItem(LocationExecutionResults locationsExecutionResultsItem) {
    if (this.locationsExecutionResults == null) {
      this.locationsExecutionResults = new ArrayList<>();
    }
    this.locationsExecutionResults.add(locationsExecutionResultsItem);
    return this;
  }

   /**
   * The list with the results of the requests executed on assigned locations.
   * @return locationsExecutionResults
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The list with the results of the requests executed on assigned locations.")
  @JsonProperty(JSON_PROPERTY_LOCATIONS_EXECUTION_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<LocationExecutionResults> getLocationsExecutionResults() {
    return locationsExecutionResults;
  }


  @JsonProperty(JSON_PROPERTY_LOCATIONS_EXECUTION_RESULTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationsExecutionResults(List<LocationExecutionResults> locationsExecutionResults) {
    this.locationsExecutionResults = locationsExecutionResults;
  }


  /**
   * Return true if this MonitorExecutionResults object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MonitorExecutionResults monitorExecutionResults = (MonitorExecutionResults) o;
    return Objects.equals(this.monitorId, monitorExecutionResults.monitorId) &&
        Objects.equals(this.locationsExecutionResults, monitorExecutionResults.locationsExecutionResults);
  }

  @Override
  public int hashCode() {
    return Objects.hash(monitorId, locationsExecutionResults);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MonitorExecutionResults {\n");
    sb.append("    monitorId: ").append(toIndentedString(monitorId)).append("\n");
    sb.append("    locationsExecutionResults: ").append(toIndentedString(locationsExecutionResults)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

