/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import com.dynatrace.apis.configv1.model.AwsAuthenticationData;
import com.dynatrace.apis.configv1.model.AwsConfigTag;
import com.dynatrace.apis.configv1.model.AwsSupportingServiceConfig;
import com.dynatrace.apis.configv1.model.ConfigurationMetadata;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AwsCredentialsConfig
 */
public class AwsCredentialsConfigTest {
    private final AwsCredentialsConfig model = new AwsCredentialsConfig();

    /**
     * Model tests for AwsCredentialsConfig
     */
    @Test
    public void testAwsCredentialsConfig() {
        // TODO: test AwsCredentialsConfig
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'connectionStatus'
     */
    @Test
    public void connectionStatusTest() {
        // TODO: test connectionStatus
    }

    /**
     * Test the property 'label'
     */
    @Test
    public void labelTest() {
        // TODO: test label
    }

    /**
     * Test the property 'partitionType'
     */
    @Test
    public void partitionTypeTest() {
        // TODO: test partitionType
    }

    /**
     * Test the property 'authenticationData'
     */
    @Test
    public void authenticationDataTest() {
        // TODO: test authenticationData
    }

    /**
     * Test the property 'taggedOnly'
     */
    @Test
    public void taggedOnlyTest() {
        // TODO: test taggedOnly
    }

    /**
     * Test the property 'tagsToMonitor'
     */
    @Test
    public void tagsToMonitorTest() {
        // TODO: test tagsToMonitor
    }

    /**
     * Test the property 'supportingServicesToMonitor'
     */
    @Test
    public void supportingServicesToMonitorTest() {
        // TODO: test supportingServicesToMonitor
    }

}
