/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import com.dynatrace.apis.configv1.model.DataExplorerQuery;
import com.dynatrace.apis.configv1.model.DataExplorerQuerySettings;
import com.dynatrace.apis.configv1.model.VisualizationConfiguration;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for DataExplorerTileAllOf
 */
public class DataExplorerTileAllOfTest {
    private final DataExplorerTileAllOf model = new DataExplorerTileAllOf();

    /**
     * Model tests for DataExplorerTileAllOf
     */
    @Test
    public void testDataExplorerTileAllOf() {
        // TODO: test DataExplorerTileAllOf
    }

    /**
     * Test the property 'customName'
     */
    @Test
    public void customNameTest() {
        // TODO: test customName
    }

    /**
     * Test the property 'queries'
     */
    @Test
    public void queriesTest() {
        // TODO: test queries
    }

    /**
     * Test the property 'visualConfig'
     */
    @Test
    public void visualConfigTest() {
        // TODO: test visualConfig
    }

    /**
     * Test the property 'queriesSettings'
     */
    @Test
    public void queriesSettingsTest() {
        // TODO: test queriesSettings
    }

    /**
     * Test the property 'metricExpressions'
     */
    @Test
    public void metricExpressionsTest() {
        // TODO: test metricExpressions
    }

}
