/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HttpErrorRule
 */
public class HttpErrorRuleTest {
    private final HttpErrorRule model = new HttpErrorRule();

    /**
     * Model tests for HttpErrorRule
     */
    @Test
    public void testHttpErrorRule() {
        // TODO: test HttpErrorRule
    }

    /**
     * Test the property 'considerUnknownErrorCode'
     */
    @Test
    public void considerUnknownErrorCodeTest() {
        // TODO: test considerUnknownErrorCode
    }

    /**
     * Test the property 'considerBlockedRequests'
     */
    @Test
    public void considerBlockedRequestsTest() {
        // TODO: test considerBlockedRequests
    }

    /**
     * Test the property 'errorCodes'
     */
    @Test
    public void errorCodesTest() {
        // TODO: test errorCodes
    }

    /**
     * Test the property 'filterByUrl'
     */
    @Test
    public void filterByUrlTest() {
        // TODO: test filterByUrl
    }

    /**
     * Test the property 'filter'
     */
    @Test
    public void filterTest() {
        // TODO: test filter
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'capture'
     */
    @Test
    public void captureTest() {
        // TODO: test capture
    }

    /**
     * Test the property 'impactApdex'
     */
    @Test
    public void impactApdexTest() {
        // TODO: test impactApdex
    }

    /**
     * Test the property 'considerForAi'
     */
    @Test
    public void considerForAiTest() {
        // TODO: test considerForAi
    }

}
