/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for JavaScriptInjectionRules
 */
public class JavaScriptInjectionRulesTest {
    private final JavaScriptInjectionRules model = new JavaScriptInjectionRules();

    /**
     * Model tests for JavaScriptInjectionRules
     */
    @Test
    public void testJavaScriptInjectionRules() {
        // TODO: test JavaScriptInjectionRules
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'urlOperator'
     */
    @Test
    public void urlOperatorTest() {
        // TODO: test urlOperator
    }

    /**
     * Test the property 'urlPattern'
     */
    @Test
    public void urlPatternTest() {
        // TODO: test urlPattern
    }

    /**
     * Test the property 'rule'
     */
    @Test
    public void ruleTest() {
        // TODO: test rule
    }

    /**
     * Test the property 'htmlPattern'
     */
    @Test
    public void htmlPatternTest() {
        // TODO: test htmlPattern
    }

    /**
     * Test the property 'target'
     */
    @Test
    public void targetTest() {
        // TODO: test target
    }

}
