/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ResourceTimingSettings
 */
public class ResourceTimingSettingsTest {
    private final ResourceTimingSettings model = new ResourceTimingSettings();

    /**
     * Model tests for ResourceTimingSettings
     */
    @Test
    public void testResourceTimingSettings() {
        // TODO: test ResourceTimingSettings
    }

    /**
     * Test the property 'w3cResourceTimings'
     */
    @Test
    public void w3cResourceTimingsTest() {
        // TODO: test w3cResourceTimings
    }

    /**
     * Test the property 'nonW3cResourceTimings'
     */
    @Test
    public void nonW3cResourceTimingsTest() {
        // TODO: test nonW3cResourceTimings
    }

    /**
     * Test the property 'nonW3cResourceTimingsInstrumentationDelay'
     */
    @Test
    public void nonW3cResourceTimingsInstrumentationDelayTest() {
        // TODO: test nonW3cResourceTimingsInstrumentationDelay
    }

    /**
     * Test the property 'resourceTimingCaptureType'
     */
    @Test
    public void resourceTimingCaptureTypeTest() {
        // TODO: test resourceTimingCaptureType
    }

    /**
     * Test the property 'resourceTimingsDomainLimit'
     */
    @Test
    public void resourceTimingsDomainLimitTest() {
        // TODO: test resourceTimingsDomainLimit
    }

}
