/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace Environment API v1. To read about use cases and examples, see [Dynatrace Documentation](https://dt-url.net/xc03k3c).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.envv1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * The baseline data for a Dynatrace entity for a specific duration metric.
 */
@ApiModel(description = "The baseline data for a Dynatrace entity for a specific duration metric.")
@JsonPropertyOrder({
  EntityBaselineData.JSON_PROPERTY_ENTITY_ID,
  EntityBaselineData.JSON_PROPERTY_DISPLAY_NAME,
  EntityBaselineData.JSON_PROPERTY_ERROR_RATE,
  EntityBaselineData.JSON_PROPERTY_HAS_LOAD_BASELINE,
  EntityBaselineData.JSON_PROPERTY_MICROS_MEDIAN,
  EntityBaselineData.JSON_PROPERTY_MICROS90TH_PERCENTILE,
  EntityBaselineData.JSON_PROPERTY_CHILD_BASELINES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-02T15:08:03.911513100+01:00[Europe/Brussels]")
public class EntityBaselineData {
  public static final String JSON_PROPERTY_ENTITY_ID = "entityId";
  private String entityId;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  private String displayName;

  public static final String JSON_PROPERTY_ERROR_RATE = "errorRate";
  private Float errorRate;

  public static final String JSON_PROPERTY_HAS_LOAD_BASELINE = "hasLoadBaseline";
  private Boolean hasLoadBaseline;

  public static final String JSON_PROPERTY_MICROS_MEDIAN = "microsMedian";
  private Float microsMedian;

  public static final String JSON_PROPERTY_MICROS90TH_PERCENTILE = "micros90thPercentile";
  private Float micros90thPercentile;

  public static final String JSON_PROPERTY_CHILD_BASELINES = "childBaselines";
  private Set<EntityBaselineData> childBaselines = null;

  public EntityBaselineData() { 
  }

  public EntityBaselineData entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * The ID of the Dynatrace entity.
   * @return entityId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The ID of the Dynatrace entity.")
  @JsonProperty(JSON_PROPERTY_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntityId() {
    return entityId;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }


  public EntityBaselineData displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name of the entity.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The display name of the entity.")
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public EntityBaselineData errorRate(Float errorRate) {
    this.errorRate = errorRate;
    return this;
  }

   /**
   * The error rate baseline.
   * @return errorRate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The error rate baseline.")
  @JsonProperty(JSON_PROPERTY_ERROR_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getErrorRate() {
    return errorRate;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorRate(Float errorRate) {
    this.errorRate = errorRate;
  }


  public EntityBaselineData hasLoadBaseline(Boolean hasLoadBaseline) {
    this.hasLoadBaseline = hasLoadBaseline;
    return this;
  }

   /**
   * The entity has a load baseline (&#x60;true&#x60;) or doesn&#39;t (&#x60;false&#x60;).
   * @return hasLoadBaseline
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The entity has a load baseline (`true`) or doesn't (`false`).")
  @JsonProperty(JSON_PROPERTY_HAS_LOAD_BASELINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getHasLoadBaseline() {
    return hasLoadBaseline;
  }


  @JsonProperty(JSON_PROPERTY_HAS_LOAD_BASELINE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasLoadBaseline(Boolean hasLoadBaseline) {
    this.hasLoadBaseline = hasLoadBaseline;
  }


  public EntityBaselineData microsMedian(Float microsMedian) {
    this.microsMedian = microsMedian;
    return this;
  }

   /**
   * The median baseline, in microseconds.
   * @return microsMedian
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The median baseline, in microseconds.")
  @JsonProperty(JSON_PROPERTY_MICROS_MEDIAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMicrosMedian() {
    return microsMedian;
  }


  @JsonProperty(JSON_PROPERTY_MICROS_MEDIAN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMicrosMedian(Float microsMedian) {
    this.microsMedian = microsMedian;
  }


  public EntityBaselineData micros90thPercentile(Float micros90thPercentile) {
    this.micros90thPercentile = micros90thPercentile;
    return this;
  }

   /**
   * The 90th percentile baseline, in microseconds.
   * @return micros90thPercentile
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The 90th percentile baseline, in microseconds.")
  @JsonProperty(JSON_PROPERTY_MICROS90TH_PERCENTILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Float getMicros90thPercentile() {
    return micros90thPercentile;
  }


  @JsonProperty(JSON_PROPERTY_MICROS90TH_PERCENTILE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMicros90thPercentile(Float micros90thPercentile) {
    this.micros90thPercentile = micros90thPercentile;
  }


  public EntityBaselineData childBaselines(Set<EntityBaselineData> childBaselines) {
    this.childBaselines = childBaselines;
    return this;
  }

  public EntityBaselineData addChildBaselinesItem(EntityBaselineData childBaselinesItem) {
    if (this.childBaselines == null) {
      this.childBaselines = new LinkedHashSet<>();
    }
    this.childBaselines.add(childBaselinesItem);
    return this;
  }

   /**
   * The baseline data for child entities of this entity, for example a &#x60;SERVICE_METHOD&#x60; of a &#x60;SERVICE_METHOD_GROUP&#x60;.
   * @return childBaselines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The baseline data for child entities of this entity, for example a `SERVICE_METHOD` of a `SERVICE_METHOD_GROUP`.")
  @JsonProperty(JSON_PROPERTY_CHILD_BASELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<EntityBaselineData> getChildBaselines() {
    return childBaselines;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_CHILD_BASELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setChildBaselines(Set<EntityBaselineData> childBaselines) {
    this.childBaselines = childBaselines;
  }


  /**
   * Return true if this EntityBaselineData object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EntityBaselineData entityBaselineData = (EntityBaselineData) o;
    return Objects.equals(this.entityId, entityBaselineData.entityId) &&
        Objects.equals(this.displayName, entityBaselineData.displayName) &&
        Objects.equals(this.errorRate, entityBaselineData.errorRate) &&
        Objects.equals(this.hasLoadBaseline, entityBaselineData.hasLoadBaseline) &&
        Objects.equals(this.microsMedian, entityBaselineData.microsMedian) &&
        Objects.equals(this.micros90thPercentile, entityBaselineData.micros90thPercentile) &&
        Objects.equals(this.childBaselines, entityBaselineData.childBaselines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, displayName, errorRate, hasLoadBaseline, microsMedian, micros90thPercentile, childBaselines);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityBaselineData {\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    errorRate: ").append(toIndentedString(errorRate)).append("\n");
    sb.append("    hasLoadBaseline: ").append(toIndentedString(hasLoadBaseline)).append("\n");
    sb.append("    microsMedian: ").append(toIndentedString(microsMedian)).append("\n");
    sb.append("    micros90thPercentile: ").append(toIndentedString(micros90thPercentile)).append("\n");
    sb.append("    childBaselines: ").append(toIndentedString(childBaselines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

