/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace Environment API v1. To read about use cases and examples, see [Dynatrace Documentation](https://dt-url.net/xc03k3c).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.envv1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dynatrace.apis.envv1.model.EntityBaselineData;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.LinkedHashSet;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * The baseline data for a service and its children for the **Response time** duration metric.
 */
@ApiModel(description = "The baseline data for a service and its children for the **Response time** duration metric.")
@JsonPropertyOrder({
  ServiceBaselineValues.JSON_PROPERTY_ENTITY_ID,
  ServiceBaselineValues.JSON_PROPERTY_DISPLAY_NAME,
  ServiceBaselineValues.JSON_PROPERTY_SERVICE_RESPONSE_TIME_BASELINES
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-02T15:08:03.911513100+01:00[Europe/Brussels]")
public class ServiceBaselineValues {
  public static final String JSON_PROPERTY_ENTITY_ID = "entityId";
  private String entityId;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
  private String displayName;

  public static final String JSON_PROPERTY_SERVICE_RESPONSE_TIME_BASELINES = "serviceResponseTimeBaselines";
  private Set<EntityBaselineData> serviceResponseTimeBaselines = null;

  public ServiceBaselineValues() { 
  }

  public ServiceBaselineValues entityId(String entityId) {
    this.entityId = entityId;
    return this;
  }

   /**
   * The ID of the service.
   * @return entityId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The ID of the service.")
  @JsonProperty(JSON_PROPERTY_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getEntityId() {
    return entityId;
  }


  @JsonProperty(JSON_PROPERTY_ENTITY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEntityId(String entityId) {
    this.entityId = entityId;
  }


  public ServiceBaselineValues displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The display name of the service.
   * @return displayName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The display name of the service.")
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDisplayName() {
    return displayName;
  }


  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }


  public ServiceBaselineValues serviceResponseTimeBaselines(Set<EntityBaselineData> serviceResponseTimeBaselines) {
    this.serviceResponseTimeBaselines = serviceResponseTimeBaselines;
    return this;
  }

  public ServiceBaselineValues addServiceResponseTimeBaselinesItem(EntityBaselineData serviceResponseTimeBaselinesItem) {
    if (this.serviceResponseTimeBaselines == null) {
      this.serviceResponseTimeBaselines = new LinkedHashSet<>();
    }
    this.serviceResponseTimeBaselines.add(serviceResponseTimeBaselinesItem);
    return this;
  }

   /**
   * The baseline data for the **Response time** duration metric.
   * @return serviceResponseTimeBaselines
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The baseline data for the **Response time** duration metric.")
  @JsonProperty(JSON_PROPERTY_SERVICE_RESPONSE_TIME_BASELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Set<EntityBaselineData> getServiceResponseTimeBaselines() {
    return serviceResponseTimeBaselines;
  }


  @JsonDeserialize(as = LinkedHashSet.class)
  @JsonProperty(JSON_PROPERTY_SERVICE_RESPONSE_TIME_BASELINES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setServiceResponseTimeBaselines(Set<EntityBaselineData> serviceResponseTimeBaselines) {
    this.serviceResponseTimeBaselines = serviceResponseTimeBaselines;
  }


  /**
   * Return true if this ServiceBaselineValues object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ServiceBaselineValues serviceBaselineValues = (ServiceBaselineValues) o;
    return Objects.equals(this.entityId, serviceBaselineValues.entityId) &&
        Objects.equals(this.displayName, serviceBaselineValues.displayName) &&
        Objects.equals(this.serviceResponseTimeBaselines, serviceBaselineValues.serviceResponseTimeBaselines);
  }

  @Override
  public int hashCode() {
    return Objects.hash(entityId, displayName, serviceResponseTimeBaselines);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ServiceBaselineValues {\n");
    sb.append("    entityId: ").append(toIndentedString(entityId)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    serviceResponseTimeBaselines: ").append(toIndentedString(serviceResponseTimeBaselines)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

