/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace Environment API v1. To read about use cases and examples, see [Dynatrace Documentation](https://dt-url.net/xc03k3c).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.envv1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Tag of a Dynatrace entity.
 */
@ApiModel(description = "Tag of a Dynatrace entity.")
@JsonPropertyOrder({
  TagInfo.JSON_PROPERTY_CONTEXT,
  TagInfo.JSON_PROPERTY_KEY,
  TagInfo.JSON_PROPERTY_VALUE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-02T15:08:03.911513100+01:00[Europe/Brussels]")
public class TagInfo {
  /**
   * The origin of the tag, such as AWS or Cloud Foundry.    Custom tags use the &#x60;CONTEXTLESS&#x60; value.
   */
  public enum ContextEnum {
    AWS("AWS"),
    
    AWS_GENERIC("AWS_GENERIC"),
    
    AZURE("AZURE"),
    
    CLOUD_FOUNDRY("CLOUD_FOUNDRY"),
    
    CONTEXTLESS("CONTEXTLESS"),
    
    ENVIRONMENT("ENVIRONMENT"),
    
    GOOGLE_CLOUD("GOOGLE_CLOUD"),
    
    KUBERNETES("KUBERNETES");

    private String value;

    ContextEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static ContextEnum fromValue(String value) {
      for (ContextEnum b : ContextEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_CONTEXT = "context";
  private ContextEnum context;

  public static final String JSON_PROPERTY_KEY = "key";
  private String key;

  public static final String JSON_PROPERTY_VALUE = "value";
  private String value;

  public TagInfo() { 
  }

  public TagInfo context(ContextEnum context) {
    this.context = context;
    return this;
  }

   /**
   * The origin of the tag, such as AWS or Cloud Foundry.    Custom tags use the &#x60;CONTEXTLESS&#x60; value.
   * @return context
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The origin of the tag, such as AWS or Cloud Foundry.    Custom tags use the `CONTEXTLESS` value.")
  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContextEnum getContext() {
    return context;
  }


  @JsonProperty(JSON_PROPERTY_CONTEXT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContext(ContextEnum context) {
    this.context = context;
  }


  public TagInfo key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The key of the tag.    Custom tags have the tag value here.
   * @return key
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The key of the tag.    Custom tags have the tag value here.")
  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getKey() {
    return key;
  }


  @JsonProperty(JSON_PROPERTY_KEY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setKey(String key) {
    this.key = key;
  }


  public TagInfo value(String value) {
    this.value = value;
    return this;
  }

   /**
   * The value of the tag.    Not applicable to custom tags.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The value of the tag.    Not applicable to custom tags.")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getValue() {
    return value;
  }


  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setValue(String value) {
    this.value = value;
  }


  /**
   * Return true if this TagInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TagInfo tagInfo = (TagInfo) o;
    return Objects.equals(this.context, tagInfo.context) &&
        Objects.equals(this.key, tagInfo.key) &&
        Objects.equals(this.value, tagInfo.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(context, key, value);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TagInfo {\n");
    sb.append("    context: ").append(toIndentedString(context)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

