/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.dynatrace.apis.configv1.model.MetricEventTextFilterMetricEventTextFilterOperatorDto;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * CustomDeviceGroupNameAlertingScopeAllOf
 */
@JsonPropertyOrder({
  CustomDeviceGroupNameAlertingScopeAllOf.JSON_PROPERTY_NAME_FILTER
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-02T15:07:55.784964900+01:00[Europe/Brussels]")
public class CustomDeviceGroupNameAlertingScopeAllOf {
  public static final String JSON_PROPERTY_NAME_FILTER = "nameFilter";
  private MetricEventTextFilterMetricEventTextFilterOperatorDto nameFilter;

  public CustomDeviceGroupNameAlertingScopeAllOf() { 
  }

  public CustomDeviceGroupNameAlertingScopeAllOf nameFilter(MetricEventTextFilterMetricEventTextFilterOperatorDto nameFilter) {
    this.nameFilter = nameFilter;
    return this;
  }

   /**
   * Get nameFilter
   * @return nameFilter
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_NAME_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public MetricEventTextFilterMetricEventTextFilterOperatorDto getNameFilter() {
    return nameFilter;
  }


  @JsonProperty(JSON_PROPERTY_NAME_FILTER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNameFilter(MetricEventTextFilterMetricEventTextFilterOperatorDto nameFilter) {
    this.nameFilter = nameFilter;
  }


  /**
   * Return true if this CustomDeviceGroupNameAlertingScope_allOf object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomDeviceGroupNameAlertingScopeAllOf customDeviceGroupNameAlertingScopeAllOf = (CustomDeviceGroupNameAlertingScopeAllOf) o;
    return Objects.equals(this.nameFilter, customDeviceGroupNameAlertingScopeAllOf.nameFilter);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nameFilter);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomDeviceGroupNameAlertingScopeAllOf {\n");
    sb.append("    nameFilter: ").append(toIndentedString(nameFilter)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

