/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Custom thresholds for TCP connection problems. If not set, automatic mode is used.    **All** of these conditions must be met to trigger an alert.
 */
@ApiModel(description = "Custom thresholds for TCP connection problems. If not set, automatic mode is used.    **All** of these conditions must be met to trigger an alert.")
@JsonPropertyOrder({
  NetworkTcpProblemsThresholds.JSON_PROPERTY_NEW_CONNECTION_FAILURES_PERCENTAGE,
  NetworkTcpProblemsThresholds.JSON_PROPERTY_FAILED_CONNECTIONS_NUMBER_PER_MINUTE
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-02T15:07:55.784964900+01:00[Europe/Brussels]")
public class NetworkTcpProblemsThresholds {
  public static final String JSON_PROPERTY_NEW_CONNECTION_FAILURES_PERCENTAGE = "newConnectionFailuresPercentage";
  private Integer newConnectionFailuresPercentage;

  public static final String JSON_PROPERTY_FAILED_CONNECTIONS_NUMBER_PER_MINUTE = "failedConnectionsNumberPerMinute";
  private Integer failedConnectionsNumberPerMinute;

  public NetworkTcpProblemsThresholds() { 
  }

  public NetworkTcpProblemsThresholds newConnectionFailuresPercentage(Integer newConnectionFailuresPercentage) {
    this.newConnectionFailuresPercentage = newConnectionFailuresPercentage;
    return this;
  }

   /**
   * Percentage of new connection failures is higher than *X*% in 3 out of 5 samples.
   * minimum: 1
   * maximum: 100
   * @return newConnectionFailuresPercentage
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Percentage of new connection failures is higher than *X*% in 3 out of 5 samples.")
  @JsonProperty(JSON_PROPERTY_NEW_CONNECTION_FAILURES_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getNewConnectionFailuresPercentage() {
    return newConnectionFailuresPercentage;
  }


  @JsonProperty(JSON_PROPERTY_NEW_CONNECTION_FAILURES_PERCENTAGE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNewConnectionFailuresPercentage(Integer newConnectionFailuresPercentage) {
    this.newConnectionFailuresPercentage = newConnectionFailuresPercentage;
  }


  public NetworkTcpProblemsThresholds failedConnectionsNumberPerMinute(Integer failedConnectionsNumberPerMinute) {
    this.failedConnectionsNumberPerMinute = failedConnectionsNumberPerMinute;
    return this;
  }

   /**
   * Number of failed connections is higher than *X* connections per minute in 3 out of 5 samples.
   * minimum: 1
   * maximum: 10000
   * @return failedConnectionsNumberPerMinute
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Number of failed connections is higher than *X* connections per minute in 3 out of 5 samples.")
  @JsonProperty(JSON_PROPERTY_FAILED_CONNECTIONS_NUMBER_PER_MINUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFailedConnectionsNumberPerMinute() {
    return failedConnectionsNumberPerMinute;
  }


  @JsonProperty(JSON_PROPERTY_FAILED_CONNECTIONS_NUMBER_PER_MINUTE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFailedConnectionsNumberPerMinute(Integer failedConnectionsNumberPerMinute) {
    this.failedConnectionsNumberPerMinute = failedConnectionsNumberPerMinute;
  }


  /**
   * Return true if this NetworkTcpProblemsThresholds object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkTcpProblemsThresholds networkTcpProblemsThresholds = (NetworkTcpProblemsThresholds) o;
    return Objects.equals(this.newConnectionFailuresPercentage, networkTcpProblemsThresholds.newConnectionFailuresPercentage) &&
        Objects.equals(this.failedConnectionsNumberPerMinute, networkTcpProblemsThresholds.failedConnectionsNumberPerMinute);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newConnectionFailuresPercentage, failedConnectionsNumberPerMinute);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkTcpProblemsThresholds {\n");
    sb.append("    newConnectionFailuresPercentage: ").append(toIndentedString(newConnectionFailuresPercentage)).append("\n");
    sb.append("    failedConnectionsNumberPerMinute: ").append(toIndentedString(failedConnectionsNumberPerMinute)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

