/*
 * Dynatrace Configuration API
 * Documentation of the Dynatrace Configuration API. To read about use-cases and examples, see [Dynatrace Documentation](https://dt-url.net/4u43kxw).  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.dynatrace.apis.configv1.model;

import java.util.Objects;
import java.util.Arrays;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


/**
 * Custom thresholds for high RDS write/read latency. If not set, automatic mode is used
 */
@ApiModel(description = "Custom thresholds for high RDS write/read latency. If not set, automatic mode is used")
@JsonPropertyOrder({
  RdsHighLatencyThresholds.JSON_PROPERTY_WRITE_READ_LATENCY
})
@javax.annotation.processing.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-11-02T15:07:55.784964900+01:00[Europe/Brussels]")
public class RdsHighLatencyThresholds {
  public static final String JSON_PROPERTY_WRITE_READ_LATENCY = "writeReadLatency";
  private Integer writeReadLatency;

  public RdsHighLatencyThresholds() { 
  }

  public RdsHighLatencyThresholds writeReadLatency(Integer writeReadLatency) {
    this.writeReadLatency = writeReadLatency;
    return this;
  }

   /**
   * Alert if read/write latency is higher than *X* milliseconds in 3 out of 5 samples.
   * minimum: 1
   * maximum: 10000
   * @return writeReadLatency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Alert if read/write latency is higher than *X* milliseconds in 3 out of 5 samples.")
  @JsonProperty(JSON_PROPERTY_WRITE_READ_LATENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWriteReadLatency() {
    return writeReadLatency;
  }


  @JsonProperty(JSON_PROPERTY_WRITE_READ_LATENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWriteReadLatency(Integer writeReadLatency) {
    this.writeReadLatency = writeReadLatency;
  }


  /**
   * Return true if this RdsHighLatencyThresholds object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RdsHighLatencyThresholds rdsHighLatencyThresholds = (RdsHighLatencyThresholds) o;
    return Objects.equals(this.writeReadLatency, rdsHighLatencyThresholds.writeReadLatency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(writeReadLatency);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RdsHighLatencyThresholds {\n");
    sb.append("    writeReadLatency: ").append(toIndentedString(writeReadLatency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

